ALTER TABLE events
ADD COLUMN IF NOT EXISTS panels JSONB NOT NULL DEFAULT '[]';

ALTER TABLE events
ADD COLUMN IF NOT EXISTS bride_name TEXT;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS groom_name TEXT;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS wedding_date DATE;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS venue_name TEXT;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS venue_address TEXT;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS venue_lat DOUBLE PRECISION;

ALTER TABLE events
ADD COLUMN IF NOT EXISTS venue_lng DOUBLE PRECISION;
